from src.endpoints.datahub_endpoint import get_thesaurus, get_hierarchy
from src.endpoints.datahub_endpoint import get_object_tags as Datahub_get_object_tags
from src.endpoints.nmvw_endpoint import get_object_tags as nmvw_get_object_tags